services:
  - type: web
    name: dirttrails-vendor-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: .build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
